import Header from '@/components/Header/Header'
import ReduxProvider from '@/store/ReduxProvider'
import './globals.css'
import {Nunito} from 'next/font/google'

const nunito = Nunito({
	subsets: ['latin'],
	weight: ['400', '700'],
	style: ['normal', 'italic'],
})

export const metadata = {
	title: 'Keyboards ecommerce',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<body className={nunito.className}>
				<ReduxProvider>
					<Header />
					{children}
				</ReduxProvider>
			</body>
		</html>
	)
}
